config/routes.rb
Rails.application.routes.draw do
  root 'thing_to_dos#homepage'

  resources :thing_to_dos
  get 'Events/homepage',      to: 'thing_to_dos#homepage'
  get  'users/new',           to: 'users#new'
  post 'users/create',        to: 'users#create'
  get  '/users/logout',       to: 'sessions#logout'
  post '/users/logout',       to: 'sessions#logout_now'
  get  '/users/login',        to: 'sessions#login'
  post '/users/login',        to: 'sessions#login_now'
  post 'add_person_to_event', to: 'thing_to_dos#add_person'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/thing_to_do.rb
class ThingToDo < ApplicationRecord
  serialize  :attending
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  serialize :going_to
  has_many  :thing_to_dos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #https://stackoverflow.com/questions/35181340/rails-cant-verify-csrf-token-authenticity-when-making-a-post-request
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def params_user
    params.require(:user).permit(:name, :password)
  end
  def params_session(session_id,user_id)
    params.permit(session_id, user_id)
  end

  def login # did this in the User controller and view...
    @user = User.new
  end
  def login_now
    @user = User.new(params_user)
    if User.exists?(name: @user.name)
      puts " \n the user is in the databace \n"
      @check = User.find_by_name(@user.name)
      if @check.authenticate(@user.password)
        puts "\n the password entered is valid \n"

        # need to make shure there arent more then one
        # need a timmer to delete automaticly in a day or 2
        @session = Session.new
        id  = SecureRandom.hex(64)
        @session.session_id = id
        puts "\n\nthe user id:  #{@check.id}\n\n"
        @session.user_id    = @check.id
        puts " save? #{@session.user_id}"
         if @session.save
           puts "save sucsessfull "
         else
           puts " not saved! "
         end

        # Save ID and random temp hash in cookie
        cookies[:session_id] = id
        puts "#{cookies[:session_id]}"
        # go to homepage
        redirect_to '/Events/homepage'
      else
        puts "\n the password entered did not match \n "
        puts "\n Entered: #{@user.password_digest} \n Check:  :#{@check.password_digest}"
        redirect_to '/users/login'
      end
    end
  end


  def logout
    @user = User.new # this is not really used... need to use a diffrent form?
  end
  def logout_now
    @session = Session.find_by(session_id: cookies[:session_id])
    if @session
      @session.destroy
      cookies.delete :session_id
      cookies.delete :key
      redirect_to "/Events/homepage"
    else
      "for some reason your session was not found"
    end
  end
end

app/controllers/thing_to_dos_controller.rb
class ThingToDosController < ApplicationController
  before_action :set_thing_to_do, only: [:show, :edit, :update, :destroy]

  def add_person
    session = Session.find_by(session_id: cookies[:session_id])
    id      = session.user_id
    puts " adding user_id #{id}\nto Event:#{params[:id]}"
    event = ThingToDo.find_by(id: params[:id])
    event.attending << id
    event.save
    redirect_to 'Events/homepage'
  end
  # GET /thing_to_dos
  # GET /thing_to_dos.json
  def index
    @thing_to_dos = ThingToDo.all
  end

  # GET /thing_to_dos/homepage
  def homepage
  end

  # GET /thing_to_dos/1
  # GET /thing_to_dos/1.json
  def show
  end

  # GET /thing_to_dos/new
  def new
    @thing_to_do = ThingToDo.new
  end

  # GET /thing_to_dos/1/edit
  def edit
  end

  # POST /thing_to_dos
  # POST /thing_to_dos.json
  def create
    session =  Session.find_by(session_id: cookies[:session_id])
    if session != nil
      user_id = session.user_id
      puts "\n\nuser id: #{session.user_id}\n\n"
      current_user = User.find_by(id: user_id)
      @thing_to_do = current_user.thing_to_dos.create(thing_to_do_params)
      # @current_session = Session.find_by session_id: cookies[:session_id]
      puts " inserting user_id: #{@thing_to_do.user_id} \n\n"

      respond_to do |format|
        if @thing_to_do.save
          format.html { redirect_to @thing_to_do, notice: 'Thing to do was successfully created.' }
          format.json { render :show, status: :created, location: @thing_to_do }
        else
          format.html { render :new }
          format.json { render json: @thing_to_do.errors, status: :unprocessable_entity }
        end
      end
    else
      puts "You need to be logged in to do that"
      redirect_to '/thing_to_dos/new', :flash => { :alert => "You need to be logged in to do tha" }
    end
  end

  # PATCH/PUT /thing_to_dos/1
  # PATCH/PUT /thing_to_dos/1.json
  def update
    respond_to do |format|
      if @thing_to_do.update(thing_to_do_params)
        format.html { redirect_to @thing_to_do, notice: 'Thing to do was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing_to_do }
      else
        format.html { render :edit }
        format.json { render json: @thing_to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thing_to_dos/1
  # DELETE /thing_to_dos/1.json
  def destroy
    @thing_to_do.destroy
    respond_to do |format|
      format.html { redirect_to thing_to_dos_url, notice: 'Thing to do was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing_to_do
      @thing_to_do = ThingToDo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_to_do_params
      params.require(:thing_to_do).permit(:name, :description, :attending, :user_id, :attending)
    end
    def attend_params
      params.require(:thing_to_dos).permit(:id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    puts "\n\n users_controller new: opening the users/new page \n\n"
    @user = User.new
  end
  def params_user
    params.require(:user).permit(:name, :password)
  end

  # how to make a loggin and session help
  # http://railscasts.com/episodes/250-authentication-from-scratch?autoplay=true
  def create
    puts "\n\n users_controller create:  running \n\n"
    # Create a new user
    @user = User.new(params_user)
    if @user.save
      # Change ID session login to true
      @session = Session.new
      # need to make shure there arent more then one
      # need a timmer to delete automaticly in a day or 2
      id  = SecureRandom.hex(64)
      key = SecureRandom.hex(64)
      @session.session_id = id
      @session.key        = key
      @session.user_id    = @user.id
      @session.save
      # Save ID and random temp hash in cookie
      cookies[:session_id] = id
      cookies[:key]        = key
      # go to homepage
      redirect_to '/Events/homepage'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thing_to_dos_helper.rb
module ThingToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navigation" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Event Manager</a>
      <ul class="nav navbar-nav">
        <li class="active"><a class="nav-item nav-link" href="/users/login">Login</a></li>
        <li class="active"><a class="nav-item nav-link" href="/users/logout">Logout</a></li>
        <li class="active"><a class="nav-item nav-link" href="/users/new">Create User</a></li>
        <li class="active"><a class="nav-item nav-link" href='/thing_to_dos/new'>Create New Event</a></li>
        <li class="active"><a class="nav-item nav-link" href='/thing_to_dos'>View Event's</a></li>
      <ul class="nav navbar-nav">
    </div>
  </div>
</nav>

app/views/thing_to_dos/_form.html.erb
<%= form_with(model: thing_to_do, local: true) do |form| %>

    <input name="authenticity_token"
       type="hidden"
       value="<%= form_authenticity_token %>"/>

  <% if thing_to_do.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thing_to_do.errors.count, "error") %> prohibited this thing_to_do from being saved:</h2>

      <ul>
      <% thing_to_do.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :thing_to_do_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :thing_to_do_description %>
  </div>




<!--
  <div class="field">
    <%= form.label :attending %>
    <%= form.number_field :attending, id: :thing_to_do_attending %>
  </div>
-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thing_to_dos/edit.html.erb
<h1>Editing Thing To Do</h1>

<%= render 'form', thing_to_do: @thing_to_do %>

<%= link_to 'Show', @thing_to_do %> |
<%= link_to 'Back', thing_to_dos_path %>

app/views/thing_to_dos/homepage.html.erb
<h1> This will be the home page </h1>

<% @current_session = Session.find_by session_id: cookies[:session_id] %>
<% if @current_session %>
  <%  puts "your cookes session id matches one in the databace" %>
  <%  @user = User.find_by id: @current_session.user_id %>
  <p><%= @user.name %>: is currently logged in</p>
<% else %>
  <p><%=  "No User is loged in!" %></p>
  <p>current: <%= @current_session %></p>
  <p>session: <%=cookies[:session_id] %></p>
<% end %>

app/views/thing_to_dos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events List</h1>

  <% @thing_to_dos.each do |thing_to_do| %>
    <div><br>
      Name:<%= thing_to_do.name %><br>
      Description:<%= thing_to_do.description %><br>
      attending:<%= thing_to_do.attending.each { |print| puts print} %><br>
      <%= link_to 'Show', thing_to_do %>
      <% if session = Session.find_by(session_id: cookies[:session_id]) %>
      <%= button_to "Attend", action: "add_person", :id => thing_to_do.id if session.user_id != nil%>
      <% end %>

        <!--
        <td><%= link_to 'Edit', edit_thing_to_do_path(thing_to_do) %></td>
        <td><%= link_to 'Destroy', thing_to_do, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         -->
    </div>
  <% end %>

app/views/thing_to_dos/new.html.erb
<h1>Create a new Event</h1>

<% session =  Session.find_by(session_id: cookies[:session_id]) %>
<% if session == nil %>
  <%= 'You need to be logged in to create an event!!' %>
<% else %>
  <%= render 'form', thing_to_do: @thing_to_do %>
<% end %>

app/views/thing_to_dos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thing_to_do.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @thing_to_do.description %>
</p>

<p>
  <strong>Attending:</strong>
  <%= @thing_to_do.attending %>
</p>

<%= link_to 'Edit', edit_thing_to_do_path(@thing_to_do) %> |
<%= link_to 'Back', thing_to_dos_path %>

app/views/users/new.html.erb
<h1> New User Page </h1>

<div class="container">

<%= form_for @user, url: 'create' do |f|  %>

<input name="authenticity_token"
       type="hidden"
       value="<%= form_authenticity_token %>"/>

 <%= f.label :name %>     <%= f.text_field :name, class: 'form-control' %>     <br>
 <%= f.label :password %> <%= f.password_field :password, class: 'form-control' %> <br>
 <%= f.submit "Create" %>
<% end %>

</div>